Moves to car, removing the dependency on Azure Pipelines
This uses OCI repositories (Docker, Homebrew) instead of relying on
Azure Pipelines zip downloads. Doing so simplifies maintenance and
complexity.

Depends on https://github.com/tetratelabs/car/pull/10

```bash
$ ./bin/archive_release_version.sh envoyproxy/envoy v1.18.3 archive
archiving envoyproxy/envoy v1.18.3 released on 2021-05-11
using dist: v1.18.3/envoy-v1.18.3-darwin-amd64
creating v1.18.3/envoy-v1.18.3-darwin-amd64.tar.xz
using dist: v1.18.3/envoy-v1.18.3-darwin-arm64
error: darwin/arm64 is not a supported platform: darwin/amd64
using dist: v1.18.3/envoy-v1.18.3-linux-amd64
creating v1.18.3/envoy-v1.18.3-linux-amd64.tar.xz
using dist: v1.18.3/envoy-v1.18.3-linux-arm64
creating v1.18.3/envoy-v1.18.3-linux-arm64.tar.xz
using dist: v1.18.3/envoy-v1.18.3-windows-amd64
creating v1.18.3/envoy-v1.18.3-windows-amd64.tar.xz
using dist: v1.18.3/envoy-v1.18.3-windows-arm64
error: windows/arm64 is not a supported platform: windows/amd64

$ find v1.18.3 -ls
35102183        0 drwxr-xr-x    7 adrian           staff                 224 Aug  3 07:11 v1.18.3
35102545    28768 -rw-r--r--    1 adrian           staff            13753856 Aug  3 07:11 v1.18.3/envoy-v1.18.3-linux-amd64.tar.xz
35103079        8 -rw-r--r--    1 adrian           staff                1120 Aug  3 07:11 v1.18.3/envoy-v1.18.3.json
35102914    16416 -rw-r--r--    1 adrian           staff             7850784 Aug  3 07:11 v1.18.3/envoy-v1.18.3-windows-amd64.tar.xz
35102748    22624 -rw-r--r--    1 adrian           staff            11492536 Aug  3 07:11 v1.18.3/envoy-v1.18.3-linux-arm64.tar.xz
35102187    38928 -rw-r--r--    1 adrian           staff            19391528 Aug  3 07:11 v1.18.3/envoy-v1.18.3-darwin-amd64.tar.xz

```

Signed-off-by: Adrian Cole <adrian@tetrate.io>